### ISSUE TITLE
Antipattern: Often mutates `this.state` directly

### ISSUE THREAD

**Issue by TimBuckley** [JaeHunRo/react-perf#1]
Frequently throughout your sourcecode, I see things like this:

```
update(index) {
	if (this.state.items[index].status === 'Active'){
		this.state.items[index].status = 'Closed';
	} else {
		this.state.items[index].status = 'Active';
	}
	this.setState(this.state);
}
```

Where `this.state` is mutated directly (e.g. `this.state.items[index].status = 'Active'`), followed by a call of `this.setState(this.state)`.

However, the [React docs](https://facebook.github.io/react/docs/component-api.html) specifically advises against this: 

> Notes:
> _NEVER_ (TB: emphasis theirs) mutate `this.state` directly, as calling `setState()` afterwards may replace the mutation you made. Treat `this.state` as if it were immutable.
> `setState()` does not immediately mutate `this.state` but creates a pending state transition. Accessing `this.state` after calling this method can potentially return the existing value.
> There is no guarantee of synchronous operation of calls to `setState` and calls may be batched for performance gains.
> `setState()` will always trigger a re-render unless conditional rendering logic is implemented in `shouldComponentUpdate()`. If mutable objects are being used and the logic cannot be implemented in `shouldComponentUpdate()`, calling `setState()` only when the new state differs from the previous state will avoid unnecessary re-renders.

Btw, thanks for your blog posts on performance! :-)

**Comment by markerikson** [comment]
Yup, was trying to figure out how to notify the author of this.

The blog posts are great, just the state mutation is bad :)

**Comment by JaeHunRo** [comment]
Thanks for pointing that out! Sorry for the super late response... lots of school work and other work going on.
Does this properly address the problem? 
549ddf950b59a948188a7d558b5571a7bec4e353

**Comment by markerikson** [comment]
Yep, at a quick glance that looks like it should work.  Thanks for updating things, and totally understand having other stuff going on :)
